from __future__ import annotations

from dataclasses import dataclass
from types import SimpleNamespace

import pytest

from muscles_ai import (
    Artifact,
    EmbeddingRequest,
    ImageGenerationRequest,
    ImageGenerationResult,
    ModelCapability,
    ModelGateway,
    ModelNotFoundError,
    OptionalProviderDependencyError,
    PythonModelAdapter,
    TextGenerationRequest,
    TextGenerationResult,
)
from muscles_ai.runtime import AiRuntime
from muscles_ai.models import ModelConfig
from muscles_ai.providers.openai import OpenAIModelAdapter


def test_gateway_routes_typed_requests_to_named_models_and_defaults() -> None:
    calls: list[tuple[str, str]] = []

    def generate_text(request, model_id):
        calls.append((request.capability, model_id))
        return TextGenerationResult(text=f"generated by {model_id}")

    def generate_image(request, model_id):
        calls.append((request.capability, model_id))
        return ImageGenerationResult(
            artifacts=[Artifact(media_type="image/png", data=b"png")],
            model=model_id,
        )

    gateway = ModelGateway()
    gateway.register_model(
        "text.local",
        PythonModelAdapter({ModelCapability.TEXT_GENERATE: generate_text}),
        model_id="qwen-local",
        capabilities=[ModelCapability.TEXT_GENERATE],
        default=True,
    )
    gateway.register_model(
        "image.local",
        PythonModelAdapter({ModelCapability.IMAGE_GENERATE: generate_image}),
        model_id="diffusion-local",
        capabilities=[ModelCapability.IMAGE_GENERATE],
    )

    text = gateway.invoke(TextGenerationRequest(prompt="hello"))
    image = gateway.invoke(ImageGenerationRequest(prompt="a cat"), model="image.local")

    assert text.text == "generated by qwen-local"
    assert image.artifacts[0].data == b"png"
    assert calls == [("text.generate", "qwen-local"), ("image.generate", "diffusion-local")]


def test_gateway_rejects_unknown_model_and_unsupported_capability() -> None:
    gateway = ModelGateway()
    gateway.register_model(
        "text",
        PythonModelAdapter(
            {ModelCapability.TEXT_GENERATE: lambda _request, _model: TextGenerationResult(text="ok")}
        ),
        model_id="text",
        capabilities=[ModelCapability.TEXT_GENERATE],
    )

    with pytest.raises(ModelNotFoundError):
        gateway.invoke(TextGenerationRequest(prompt="hello"), model="missing")

    with pytest.raises(ValueError, match="does not support capability"):
        gateway.invoke(EmbeddingRequest(texts=["hello"]), model="text")


def test_gateway_rejects_capability_not_implemented_by_adapter() -> None:
    gateway = ModelGateway()
    gateway.register_model(
        "misconfigured",
        PythonModelAdapter(
            {ModelCapability.TEXT_GENERATE: lambda _request, _model: TextGenerationResult(text="ok")}
        ),
        model_id="text",
        capabilities=[ModelCapability.IMAGE_GENERATE],
    )

    with pytest.raises(ValueError, match="Provider adapter.*does not support capability"):
        gateway.invoke(ImageGenerationRequest(prompt="cat"), model="misconfigured")


def test_gateway_supports_configured_fake_provider_without_loading_optional_sdk() -> None:
    gateway = ModelGateway.from_config(
        providers={"fake": {"type": "fake", "options": {"answer_prefix": "test"}}},
        models={
            "text.fake": {
                "provider": "fake",
                "model": "fake-model",
                "capabilities": ["text.generate"],
            }
        },
        defaults={"text.generate": "text.fake"},
    )

    result = gateway.invoke(TextGenerationRequest(prompt="hello"))

    assert isinstance(result, TextGenerationResult)
    assert result.text.startswith("test")
    assert gateway.inspect()["models"][0]["name"] == "text.fake"


def test_optional_provider_dependency_is_reported_at_use_time() -> None:
    gateway = ModelGateway.from_config(
        providers={"llama": {"type": "llama_cpp", "options": {"model_path": "model.gguf"}}},
        models={
            "text.local": {
                "provider": "llama",
                "model": "local",
                "capabilities": ["text.generate"],
            }
        },
        defaults={"text.generate": "text.local"},
    )

    with pytest.raises(OptionalProviderDependencyError):
        gateway.invoke(TextGenerationRequest(prompt="hello"))


def test_python_adapter_can_return_structured_artifacts() -> None:
    @dataclass(frozen=True)
    class CustomResult:
        value: str

    gateway = ModelGateway()
    gateway.register_model(
        "custom",
        PythonModelAdapter(
            {
                ModelCapability.TEXT_GENERATE: lambda _request, _model: CustomResult("custom")
            }
        ),
        model_id="custom-model",
        capabilities=[ModelCapability.TEXT_GENERATE],
    )

    result = gateway.invoke(TextGenerationRequest(prompt="hello"), model="custom")

    assert result.value == "custom"


def test_ai_runtime_builds_gateway_from_provider_and_model_config() -> None:
    runtime = AiRuntime(
        key="ai",
        providers={"fake": {"type": "fake", "options": {"answer_prefix": "configured"}}},
        models={
            "text.configured": {
                "provider": "fake",
                "model": "configured-model",
                "capabilities": ["text.generate"],
            }
        },
        defaults={"text.generate": "text.configured"},
    )

    result = runtime.model_gateway.generate_text("hello")

    assert result.text.startswith("configured")
    assert runtime.model_gateway.inspect()["models"][0]["name"] == "text.configured"


def test_openai_adapter_normalizes_text_image_and_embedding_results() -> None:
    class FakeResponses:
        def create(self, **kwargs):
            assert kwargs["model"] == "text-model"
            return SimpleNamespace(output_text="hello from api")

    class FakeImages:
        def generate(self, **kwargs):
            assert kwargs["model"] == "image-model"
            return SimpleNamespace(data=[SimpleNamespace(b64_json="aGVsbG8=")])

    class FakeEmbeddings:
        def create(self, **kwargs):
            assert kwargs["model"] == "embedding-model"
            return SimpleNamespace(
                data=[SimpleNamespace(index=0, embedding=[0.1, 0.2])]
            )

    client = SimpleNamespace(
        responses=FakeResponses(),
        images=FakeImages(),
        embeddings=FakeEmbeddings(),
    )
    model = ModelConfig(
        name="api",
        provider="openai",
        model_id="text-model",
        capabilities=frozenset(
            [
                ModelCapability.TEXT_GENERATE,
                ModelCapability.IMAGE_GENERATE,
                ModelCapability.TEXT_EMBED,
            ]
        ),
    )
    adapter = OpenAIModelAdapter({}, model, client=client)

    text = adapter.invoke(TextGenerationRequest(prompt="hello"), model_id="text-model", options={})
    image = adapter.invoke(
        ImageGenerationRequest(prompt="cat"), model_id="image-model", options={}
    )
    embeddings = adapter.invoke(
        EmbeddingRequest(texts=["hello"]), model_id="embedding-model", options={}
    )

    assert text.text == "hello from api"
    assert image.artifacts[0].data == b"hello"
    assert embeddings.vectors == [[0.1, 0.2]]
